server:
  port: 8081

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true