server:
  port: 8081  # ???? core-service (?? ??????????? ? Gateway)

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5433/core_service_db  # URL ????? ??
    username: postgres  # ????? ??? ???????????
    password: 1337  # ??????
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update  # ?????????????? ?????????? ????? ??
      show-sql: true  # ?????????? SQL-??????? ? ?????